language: node_js
node_js:
  - lts/*

branches:
  only:
    - master

before_script:
  - npm i -g firebase-tools
  - npm i -g gulp-cli
  - cd functions && npm i && cd ..

script:
  - npm run build

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
