# Site
baseURL: "https://livedesign.com.br"
languageCode: "pt-BR"
title: "Live Design"
googleAnalytics: "UA-104410576-1"

# Custom variables
params:
  description: "Projetos de Identidade Visual"
  themeColor: "#ffffff"

# Build Configuration
cleanDestinationDir: true
disableHugoGeneratorInject: true
enableRobotsTXT: true
publishdir: "dist"
minify: true
disableKinds: [taxonomy, term, RSS]
