# Site
baseURL: "https://live-design.web.app"
languageCode: "pt-BR"
title: "Live Design"
googleAnalytics: "G-RWJZJJGP3H"

# Custom variables
params:
  description: "Projetos de Identidade Visual"
  themeColor: "#ffffff"

# Menu settings
menu:
  main:
    - identifier: home
      name: Home
      url: "#main-section"

    - identifier: about
      name: Sobre
      url: "#about"

    - identifier: portfolio
      name: Portfólio
      url: "#portfolio"

# Build Configuration
cleanDestinationDir: true
disableHugoGeneratorInject: true
enableRobotsTXT: true
publishdir: "dist"
minify: true
disableKinds: [taxonomy, term, RSS]
